//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type ExercisesRepsCollections struct {
	ID           string `sql:"primary_key"`
	AdminID      string
	CollectionID string
	ExerciseID   string
	Reps         int32
	Sets         int32
}
