//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Gyms struct {
	ID          string `sql:"primary_key"`
	AdminID     string
	Name        string
	Description string
	Location    string
	Number      string
	Img         string
}
