//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Plans struct {
	ID          string `sql:"primary_key"`
	GymID       string
	Name        string
	Description string
	Price       float64
	Duration    int32
	Img         string
}
