//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Users struct {
	ID          string `sql:"primary_key"`
	GymID       *string
	Name        string
	Email       string
	Role        string
	Password    string
	PlanID      *string
	LastPayment *time.Time
	CreatedAt   *time.Time
}
